{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-baseline.fullname" . }}-cluster-admin-group
  labels:
    {{- include "cluster-baseline.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
{{- range .Values.rbac.adminGroups }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ . }}
{{- end }}
{{- end }}
